### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [programmingwang/gythtglxt#30]
Hi,<br><br>url : https://github.com/programmingwang/gythtglxt/blob/adee8efcb3f4a0202d85ea6f59b3ccd4f8a7ea59/src/main/resources/application.yml <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by programmingwang** [comment]
thank you so much,but i dont have visa card to use Paypal or u can give me your alipay account, i can buy you a coffee


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "programmingwang/gythtglxt"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月17日(星期天) 晚上10:16
收件人:&nbsp;"programmingwang/gythtglxt"<gythtglxt@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[programmingwang/gythtglxt] Security Data Issues Secrets in clear text (#30)





 
Hi,

url : https://github.com/programmingwang/gythtglxt/blob/adee8efcb3f4a0202d85ea6f59b3ccd4f8a7ea59/src/main/resources/application.yml 

You have commit that need to remove from the github history
attacker can see it and use it ...

encrypt your secrets !!!!

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by shaybenb** [comment]
any time , this is why we are here :)
i am sorry but i cant create alipay account, if you have Paypal https://www.paypal.com/paypalme/bugbounty1

if not its ok :)
